openapi: 3.0.3
info:
  title: PhishProof MFA Banking API - WebAuthn Authentication
  version: 1.0.0
  description: API contract for WebAuthn authentication

paths:
  /api/webauthn/auth/challenge:
    post:
      summary: Generate WebAuthn authentication challenge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: WebAuthn credential ID of the user to authenticate
              required:
                - userId
      responses:
        '200':
          description: Authentication challenge generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  challenge:
                    type: string
                    description: Base64URL encoded challenge
                  allowCredentials:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          example: "public-key"
                        id:
                          type: string
                          description: Base64URL encoded credential ID
                  timeout:
                    type: integer
                    example: 60000
                  userVerification:
                    type: string
                    example: "preferred"
                required:
                  - challenge
                  - allowCredentials
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found"

  /api/webauthn/auth/verify:
    post:
      summary: Verify WebAuthn authentication response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  type: object
                  description: WebAuthn assertion response from navigator.credentials.get()
                  properties:
                    id:
                      type: string
                    rawId:
                      type: string
                    type:
                      type: string
                    response:
                      type: object
                      properties:
                        clientDataJSON:
                          type: string
                        authenticatorData:
                          type: string
                        signature:
                          type: string
                        userHandle:
                          type: string
                challenge:
                  type: string
                  description: Original challenge used for authentication
              required:
                - credential
                - challenge
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  token:
                    type: string
                    description: JWT session token
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      balance:
                        type: number
                        format: float
                  expiresAt:
                    type: string
                    format: date-time
                    description: Token expiration time
                required:
                  - success
                  - token
                  - user
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid credential"